### ISSUE TITLE
Will LAION-Glyph datasets and training code be released in the near future?

### ISSUE THREAD

**Issue by ningyu1991** [AIGText/GlyphControl-release#1]
Thank you for your great contributions! To further inspire the community, I am wondering if LAION-Glyph datasets and training code will be released in the near future?

**Comment by PkuRainBow** [comment]
We plan to release the LAION-Glyph datasets within the next ~1 week. The training code will be released later.

**Comment by PkuRainBow** [comment]
@guidongnan Please follow this thread!

**Comment by XIRZC** [comment]
> We plan to release the LAION-Glyph datasets within the next ~1 week. The training code will be released later.

Thanks for your great work. As you said that datasets will be released within 1 week, I sincerely ask how long it will take for it to be released.

**Comment by PkuRainBow** [comment]
@guidongnan Dongnan is still preparing the training dataset. We will try to release the training data by this weekend.

**Comment by XIRZC** [comment]
> @guidongnan Dongnan is still preparing the training dataset. We will try to release the training data by this weekend.

Thanks.

**Comment by ningyu1991** [comment]
Your work is really appreciated. Looping back to see the readiness of your LAION-Glyph datasets? Thanks in advance!

**Comment by PkuRainBow** [comment]
@ningyu1991 Thanks for your interest and we are really sorry for the delayed schedule due to the personnel changes.

I will try to find additional bandwidth to follow up on this thread.

**Comment by PkuRainBow** [comment]
We have released the LAION-Glyph benchmark. @ningyu1991 @XIRZC

**Comment by PkuRainBow** [comment]
Please try the updated link! @ningyu1991 @XIRZC
