### ISSUE TITLE
About the training time

### ISSUE THREAD

**Issue by LazyChild** [AIGText/GlyphControl-release#10]
Excellent work!
But I am confused about the training time that you spend. The only information related to the training duration that I see in the text is "The training of stable-diffusion-2-base costs hundreds of hours with 128× A100 GPUs." However, this seems to have no relation to GlyphControl.

**Comment by yukang123** [comment]
Thanks for your questions. Yes, we only training the Glyph ControlNet part. The training time depends on the training dataset and available GPUs. For the case of training on LaionGlyph 1M, we used 8 cluster nodes, each of which has 8 32G V100s. On each GPU, the batch size is 16. Each epoch took around 3 hours and in the end it took around 64 hours to train the model for 20 epochs. 

I hope that this information could be a useful reference for you.
