### ISSUE TITLE
About the hyperparameters ’caption_drop_rates‘

### ISSUE THREAD

**Issue by Zhaohuii-Wang** [AIGText/GlyphControl-release#11]
Thank you very much for opening up the training code and dataset.
I noticed several hyperparameters in config: caption_choices,caption_drop_rates and its associated rendered_txt_in_caption (but it doesn't seem to be used). I found that through drop_rates, the code randomly sets caption to empty and injects caption of two kinds of drop_rate into controlnet and unet, respectively. What is the purpose of this?

**Comment by yukang123** [comment]
Thanks for your questions. Dropping 10% captions in the original UNet pathway was aimed to train the unconditional model for classifier-free guidance. We also follow original ControlNet paper to replace 50% captions with empty strings. The below is explanation in the original ControlNet paper https://arxiv.org/pdf/2302.05543.pdf. 
<img width="607" alt="截屏2024-04-08 17 52 33" src="https://github.com/AIGText/GlyphControl-release/assets/39018085/0b964b78-238c-433e-abdd-9783f867c9cf">
