### ISSUE TITLE
Question about downloading dataset

### ISSUE THREAD

**Issue by Question406** [AIGText/GlyphControl-release#4]
Hi, thanks for the great work.

Could you add some instructions about downloading dataset? I failed to download it and found this error.

<img width="743" alt="image" src="https://github.com/AIGText/GlyphControl-release/assets/15529162/d645f7f1-49fb-4761-9684-23dc43dc9014">

**Comment by PkuRainBow** [comment]
Please try the updated link!

**Comment by Question406** [comment]
it works, thanks
